name: Buildx And Publish chromium-headless-arm64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master 
    - name: Customizable Docker Buildx
      uses: ilteoood/docker_buildx@1.0.4
      with:
        tag: latest
        imageName: bianzhifu/chromium-headless-arm64 
        dockerFile: Dockerfile
        publish: true
        platform: linux/arm64
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
